[project]
name = "real-estate-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.26",
    "pandas>=2.0",
    "matplotlib>=3.8",
    "seaborn>=0.13",
    "scikit-learn==1.9.0",
    "plotly>=5.22",
    "streamlit==1.65.0",
    "ipykernel",
    "jupyter",
    "nbformat",
    "wordcloud"
]
